---
apiVersion: v1
kind: Namespace
metadata: 
  name: flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-app
  name: python-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
      replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-app
    spec:
      containers:
        - name: python-app
          image: bhargavibairagoni/pythonapp:flask
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: flask-app
  name: python-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector: 
    api.kubernetes.io/name: python-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: flask-app
  name: ingress-app
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
      paths: 
        - path: /
          pathType: Prefix
          backend: 
            service: 
              name: python-service
              port:
                number: 80
