---
apiVersion: v1
kind: Namespace
metadata: 
  name: flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-app
  name: python-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
      replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-app
    spec:
      containers:
        - name: cont2
          image: bhargavibairagoni/pythonapp:flask
          ports:
            - containerPort: 6000
