---
apiVersion: v1
kind: Namespace
metadata: 
  name: flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-app
  name: python-app
spec:
  replicas: 2  # Moved outside 'selector'
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-app
    spec:
      containers:
        - name: python-app
          image: 905418365089.dkr.ecr.us-east-1.amazonaws.com/flask-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: flask-app
  name: python-service
spec:
  selector:  # Fixed label to match Deployment
    app.kubernetes.io/name: python-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
