users:
- name: my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: aws
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
